name: kaatane
description: Kaatane application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.13

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.0+1
  provider: ^3.0.0
  http: ^0.12.0+4
  #js: ^0.6.0
  #shared_preferences: ^0.5.6
  shared_preferences: ^0.5.12
  introduction_screen: ^1.0.7
  flutter_paystack: ^1.0.4+1
  firebase_database: ^3.1.1
  url_launcher: ^5.4.1
  flare_flutter: ^2.0.3
  intl:
  carousel_slider: 2.3.1

  custom_switch: ^0.0.1
  flutter_slidable: ^0.5.4
  firebase_auth: ^0.16.0
  uuid: ^2.0.4
  timeago: ^2.0.26
  image_cropper: ^1.2.1
  image_picker: 0.6.0+17
  flutter_colorpicker: ^0.3.4
  firebase_storage: 3.0.4
  firebase_messaging: ^5.0.2
  sqflite: ^1.2.0
  firebase_crashlytics: ^0.1.1+1
  #firebase_admob: ^0.9.0+1
  flutter_datetime_picker: ^1.3.8
  google_fonts: ^1.1.0
  flutter_phone_state: ^0.5.9
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/kaatane_splash_bg.png
    - assets/images/kaatane_white.png
    - assets/images/restaurant_logo.png
    - assets/images/placeholder.png
    - assets/images/login_bg.jpg
    - assets/images/login_bg_2.png
    - assets/images/order_icon.png
    - assets/images/pick_restaurant_1.png
    - assets/images/pick_restaurant_2.png
    - assets/images/pick_restaurant_3.png
    - assets/images/pay_online.png
    - assets/images/empty_cart.png
    - assets/images/delivery_icon.png
    - assets/images/delivery_fee_icon.png
    - assets/doc/Privacy Policy.pdf
    - assets/doc/Terms of Service.pdf
    - assets/flare/logo_loading.flr
    - assets/flare/f1.flr
    - assets/flare/Teddy.flr
    - assets/flare/tick.flr
    - assets/flare/New0000.flr
    - assets/images/drawer/add_user.png
    - assets/images/drawer/get_help.png
    - assets/images/drawer/Info.png
    - assets/images/drawer/login.png
    - assets/images/drawer/orders.png
    - assets/images/drawer/drawer_img.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Consola
      fonts:
        - asset: assets/fonts/CONSOLA.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
