import 'package:flutter/material.dart';

class TermOfUse extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("Privacy Policy"), centerTitle: true,),
    body:ListView(
      children: <Widget>[
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 16),
          child: Container(
            child: Text("""Eligibility: The User must undertake to adhere to the eligibility to enter into a contract in view of section 11 of The Indian Contract Act, 1872. The User shall agree to represent and warrant that the User is at the age of 18 or above and is fully able and competent to understand and agree the terms, conditions, obligations, affirmations, representation and warranties as set forth in this Agreement.
Compliance of Law: Both the User and the Kaatane must be in compliance with all laws and regulations in the country in which they live while accessing and using the Service. The User must agree to use the Services only in compliance with terms & conditions, applicable law, and in a manner that does not violate legal rights or those of any third party/parties.
Legal implications of online food ordering: The Kaatane shall state in its Agreement that it provides online food ordering services by entering into contractual arrangements with Restaurants on a principal to principal basis for the purpose of listing their food and beverages for online ordering by the Users on the Kaatane (“Restaurant Partners”). The Users can access the list of food and beverages of the Restaurant Partners listed on Kaatane and place orders against the Restaurant Partners through Kaatane which the Restaurant Partner may or may not accept at its absolute discretion. 
User’s request to order food and beverages from a Restaurant Partner by clicking on ‘Place Order’ tab on the Restaurant Partner page on the Kaatane shall constitute an unconditional and irrevocable authorization issued in favor of Kaatane to place online orders for food and beverages against the Restaurant Partners on User’s behalf. An order, when placed on behalf of User by the Kaatane and accepted by a Restaurant Partner constitutes a separate contract of sale of goods under the Sale of Goods Act,1930 and the Consumer Protection Act, 2019 or any successor legislation between the Restaurant Partner and the User, to which Kaatane is not a party. 

The Kaatane shall make it clear that it is not a manufacturer, seller or distributor of food or beverages and merely places an order against the Restaurant Partner on behalf of the User pursuant to the aforesaid contract and facilitate the sale and purchase of food and beverages between User and Restaurant Partners, under the contract for sale and purchase of food and beverages between the User and Restaurant Partners. 

The Kaatane shall not be liable for any actions or omissions by the Restaurant Partners including deficiency in service, wrong delivery or order, quality of food, time taken to prepare or deliver the order etc. 

The Kaatane must state that the liability of any violation of the Food Safety and Standards Act, 2006 and applicable rules and regulations made thereunder shall solely be of the seller/owners, vendors, Restaurant Partners, importer or manufacturers of the food products. 

The Kaatane must disclaim in respect of some of the food that may be suitable for certain ages only. It must be the responsibility of User to check the food they are ordering and read its description, if provided, before placing order on Kaatane. The Kaatane shall not be liable in the event food ordered buy User does not meet User’s dietary or any other requirements and/or restrictions.  

The User must warrant that while placing order the details like contact number, delivery address etc. are accurate and correct. By providing these details, the User expresses his/her acceptance to Kaatane’s terms and conditions and privacy policies. 

The User shall not resell food purchased via Kaatane. 

The Kaatane must state that Delivery of an order placed by the User through Kaatane may either be undertaken directly by the Restaurant Partner against who the User has place the order, or facilitated by the Kaatane through third-party (“Restaurant Partners”) who may be available to provide delivery services to User (“Delivery Partner”). In both cases, the Kaatane is merely acting as an intermediary between the User and the Delivery Partners, or the User and the Restaurant Partners, as the case may be.

The acceptance by a Delivery Partner of undertaking delivery of User’s order shall constitute a contract of service under the Consumer Protection Act, 2019 or any successor legislations, between the User and the Delivery Partner, to which again Kaatane is not a party. 

Kaatane must clarify that Kaatane does not provide any delivery or logistics services and only enables the delivery of food and beverages ordered by the Users through Kaatane by connecting User with Delivery Partners or the Restaurant Partners, as the case may be.

The Kaatane shall not be liable for any acts or omissions on part of the Delivery Partner or Restaurant Partner including but not limited to deficiency in service, wrong delivery of order, delay in reaching order, order package tampering etc. 

The User may be charged a delivery fee for delivery of order by the Delivery Partner or Restaurant Partner as the Delivery Partner or Restaurant Partner may determine (“Delivery Charges”). The User must agree that Kaatane is authorized to collect, on behalf of the Delivery Partner or Restaurant Partner, as the case may be. The Delivery Charges may vary from, order to order, which may be determined on multiple factors such as order value, demand during peak hours etc. The Kaatane must state that it will use reasonable efforts to inform the User of the Delivery Charges that may apply to the User, provided the User will be responsible for Delivery Charges incurred for User’s order regardless of User’s awareness of such Delivery Charges.

Intellectual & Proprietary Rights: The Kaatane must declare its ownership of Kaatane content and Proprietary Rights in detail and the User must agree to protect Kaatane’S IPR and proprietary rights.

License: Kaatane shall grant User a personal, limited, non-exclusive, and non-transferrable license to access and use the Services only as expressly permitted as per the terms and conditions of the Agreement. The user must agree not to use the services for an illegal purpose or in any manner inconsistent with the terms and conditions of this Agreement.
Kaatane shall reserves it’s right that at any time and without prior notice, the Kaatane can remove, block, or disable access to any Content, for any reason or no reason, considered to be objectionable, in violation of the terms and conditions of this Agreement or otherwise harmful to the Services.
Review and Ratings: The review or ratings for restaurant by User do not reflect the opinion of Kaatane. Kaatane gets many reviews or ratings for Restaurant by User, which reviews or ratings for Restaurants by Users, which shows the views of the User. It is important to state that every review or ratings posted on Kaatane is the personal view of the User. 
On-Time Delivery: The User may opt for on-time delivery services offered by the Kaatane, for an additional non-refundable cost, at selected Restaurants. The User shall however acknowledge that such services are offered by the Kaatane on a best effort basis, hence should the order fail to reach on or prior to the Promise Time, the User would be eligible to receive Coupon worth value or upto INR 200, whichever is lower. The Coupon is required to be claimed within 24 hours from the time such Order is delivered failing which the eligibility to receive Coupon expires. The User shall not be eligible to receive the coupon, if Kaatane fails to deliver such Order within Promise Time for unforeseen reasons beyond the control of Kaatane eg. Strikes, natural disaster etc.
Price List: Kaatane take cares to keep all the prices listed are correct at the time of publication, and have been placed as received from the Restaurants. The final price charged to the User may change at the time of delivery. In the event of conflict between prices of the Kaatane and price charged by the Restaurant, the price charged by the Restaurant shall be deemed to be the correct price except Delivery Charge of Kaatane. The total price for food ordered, including the Delivery Charges and other charges, will be displayed on the Kaatane when you place your order, which shall be rounded up to the nearest rupee. User shall make full payment towards such food ordered via the Kaatane. Any amount that may be charged to the User by Kaatane over and above the order value shall be inclusive of applicable taxes. 
Delivery periods/Pickup time quoted at the time of ordering are approximate only, and may vary. When the User opts for Pickup at the time of placing the Order, and Kaatane shall not be liable in any manner in this regard. 
Personal Promo Code/offers/memberships can be used by the User subject to such terms and conditions set forth by Kaatane from time to time. The Kaatane can promote its new offers/membership plans etc. and the User will have to subscribe for the same. The subscribers will only be eligible for offers opted.
Order cancellation: The User must acknowledge that any cancellation or attempted or purported cancellation of an Order shall amount to breach of User’s unconditional and irrevocable authorization in favor of the Kaatane to place that Order against the Restaurant Partners on User’s behalf (“Authorization Breach”). In the event the User commit an Authorization Breach, the User shall be liable to pay the liquidated damages of an amount equivalent to the Order Value. The User must undertake to authorize Kaatane to deduct or collect the amount payable as liquidate damages through such means as Kaatane may determine in its discretion, including without limitation, by deducting such amount from payment made towards User’s next order. The Kaatane shall not facilitate replacements/ refunds/ or any other resolution without Restaurant’s Partner permission. All refunds shall be processed in the same manner as they are received, unless refunds have been provided to the User in the form of credits, refund amount will reflect in User’s account based on respective bank policies.
Statutory Compliances by Restaurant Partners: The User acknowledges that Kaatane bears no responsibility for the compliance with statutory rules, regulations and licenses by the Restaurant Partners. The User agrees that Kaatane shall not be liable in any manner if the User is unable to avail the offer(s) with a Restaurant Partners due to Restaurant Partner’s violation of any statutory rule, regulation and license. 
Limitation of Liability: The Kaatane shall in no manner be liable in any way for any in-person interactions with representatives or staff of the Restaurant Partners or for the member’s experience at the Restaurant Partners. The Kaatane in no manner be liable to the member if any outlet of Restaurant Partners temporarily or permanently shuts down its operations. The Kaatane will only take care of claims/liabilities arising out of offers/membership plans advertised by Kaatane solely.
Assignment: The Kaatane may assign of its right obligations under these terms and conditions to any of its affiliates or any third party at any time.
Food hygiene audit of Restaurant Partners:  The Kaatane shall undertake to initiate food hygiene auditing of Restaurant Partners in partner with certified auditors. 
Disclaimer of warranties, limitation of liability and indemnification: Disclaimer of warranties: the User must acknowledge and agree that the Services are provided “as is” and “as available” and that the use of the Services shall be at the risk of User. To the fullest extent permitted by applicable law, the Kaatane, its affiliates and their respective officers, directors, employees, agents, affiliates, branches, subsidiaries and licensor (“Kaatane Parties”) disclaims warranties, express or implied, in connection with the Services including mobile apps and User’s use of them. To the fullest extent permitted by applicable law, the Kaatane parties makes no warranties or representations that the Services have been or will be provided with due skill, care and diligence or about the accuracy or completeness of the Services content and assume no responsibility for any (i) errors, mistakes, or inaccuracies of Content, (ii) personal injury of property damage, of any nature, whatsoever, resulting from User’s access to and use of the services, (iii) any unauthorized access to or use of Kaatane’s server and/or any and all personal information stored therein, (iv) any interruption or cessation of transmission to or from the Services, (v) any bugs, viruses, Trojan Horses, or the like which may be transmitted to or through the Services, through the action of an third party,(v) any loss of User’s data or Content from the Services and/or, (vii) an errors or omissions in any content or for any loss or damage of any kind incurred as a result of the use of any content posted, emailed, transmitted or otherwise made available via the Services. 
           """, textAlign: TextAlign.justify,),
          ),
        ),
      ],
    ),
    );
  }
}
